# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Estcado
title: Estcado
email: estcado@gmail.com
location: Blaarthemseweg 16b, 5654 NT, Eindhoven
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nboskovic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# blog_url: "/blog"
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"
permalink: /
encoding: UTF-8

# sass styles
sass:
    sass_dir: _sass
    style: compressed

# social sites
instagram_username: estcado_tattoo


# Build settings
permalink: pretty
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# front image
front_img: yes
front_img_path: "images/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# favicon
favicon_img: yes
favicon_img_path: "images/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md 
  - .gitignore
include: ["_pages"]
